# Generated by Django 4.0 on 2022-04-23 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=256)),
                ('email', models.EmailField(max_length=254)),
                ('gender', models.CharField(default='NA', max_length=10)),
                ('status', models.CharField(max_length=20)),
            ],
        ),
    ]
